/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.tsmendoza.sistemaregistro.presentacion;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleFactura;
import modelo.Factura;
import ec.edu.tsmendoza.sistemaregistro.negocio.FacturaServicio;

/**
 *
 * @author Dell Inspiron 16
 */
public class Facturas_frm extends javax.swing.JInternalFrame {

    /**
     * Creates new form Facturas_frm
     */
    public static DefaultTableModel modelo;
    private List<Factura> listadoFacturas;

    public Facturas_frm() {
        initComponents();
        FacturaServicio servicio = new FacturaServicio();
        List<Factura> listaFacturas = servicio.obtenerFacturasConDetalles();
        mostrarDatos(listaFacturas);
    }

    private void mostrarDatos(List<Factura> listaFacturas) {
        listadoFacturas = listaFacturas;
        modelo = new DefaultTableModel();
        modelo.addColumn("Cedula");     //0
        modelo.addColumn("Nombre");     //1
        modelo.addColumn("Apellido");   //2
        modelo.addColumn("Correo");     //3
        modelo.addColumn("Edad");       //4
        modelo.addColumn("Modelo");   //5
        modelo.addColumn("Precio U");   //6
        modelo.addColumn("Cantidad");   //7

        for (Factura fact : listaFacturas) {
            for (DetalleFactura detalle : fact.getDetalles()) {
                Object[] fila = {
                    fact.getPersona().getCedula(),
                    fact.getPersona().getNombre(),
                    fact.getPersona().getApellido(),
                    fact.getPersona().getCorreo(),
                    fact.getPersona().getEdad(),
                    detalle.getProducto().getNombre(),
                    detalle.getPrecioUnitario(),
                    detalle.getCantidad()
                };
                modelo.addRow(fila);
            }
        }

        tbl_facturas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_facturas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas");

        tbl_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_facturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_facturas;
    // End of variables declaration//GEN-END:variables
}
