/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.tsmendoza.sistemaregistro.presentacion;

import java.util.ArrayList;
import java.util.List;
import ec.edu.tsmendoza.sistemaregistro.negocio.FacturaServicio;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Dell Inspiron 16
 */
public class Factura_frm extends javax.swing.JInternalFrame {

    /**
     * Creates new form SistemaFactura
     */
    private List<DetalleFactura> detallesFactura = new ArrayList<>();

    private Persona personaEncontrada;

    private final FacturaServicio servicio;

    private Producto productoEncontrado;

    public static DefaultTableModel modelo;

    public Factura_frm() {
        initComponents();
        servicio = new FacturaServicio();
        DeshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        butt_buscarCedula = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        butt_buscarCodigo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        butt_agregarDetalle = new javax.swing.JButton();
        butt_crearFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalle = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_persona = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        butt_eliminarPersona = new javax.swing.JButton();
        butt_eliminarProd = new javax.swing.JButton();
        lb_infProducto = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Factura");

        jLabel1.setText("Numero de cedula:");

        butt_buscarCedula.setText("Buscar");
        butt_buscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_buscarCedulaActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo:");

        butt_buscarCodigo.setText("Buscar");
        butt_buscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_buscarCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Precio:");

        txt_precio.setEditable(false);

        butt_agregarDetalle.setText("Agregar");
        butt_agregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_agregarDetalleActionPerformed(evt);
            }
        });

        butt_crearFactura.setText("Crear Factura");
        butt_crearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_crearFacturaActionPerformed(evt);
            }
        });

        tbl_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_detalle);

        tbl_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_persona);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Datos del Cliente:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Listado Productos:");

        butt_eliminarPersona.setText("Eliminar");
        butt_eliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_eliminarPersonaActionPerformed(evt);
            }
        });

        butt_eliminarProd.setText("Eliminar");
        butt_eliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_eliminarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(butt_buscarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(lb_infProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(butt_crearFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_precio))
                            .addComponent(txt_cedula)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butt_buscarCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butt_eliminarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butt_agregarDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butt_eliminarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butt_buscarCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_eliminarPersona)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butt_buscarCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_infProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(butt_agregarDetalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_eliminarProd)
                        .addGap(23, 23, 23)
                        .addComponent(butt_crearFactura))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeshabilitarBotones() {
        butt_eliminarPersona.setEnabled(false);
        butt_eliminarProd.setEnabled(false);
        butt_buscarCodigo.setEnabled(false);
        butt_agregarDetalle.setEnabled(false);
        butt_crearFactura.setEnabled(false);
        butt_buscarCedula.setEnabled(true);
    }

    private void butt_buscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_buscarCedulaActionPerformed
        // TODO add your handling code here:
        BuscarPersona();
    }//GEN-LAST:event_butt_buscarCedulaActionPerformed

    private void butt_buscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_buscarCodigoActionPerformed
        // TODO add your handling code here:
        BuscarProducto();
    }//GEN-LAST:event_butt_buscarCodigoActionPerformed

    private void butt_agregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_agregarDetalleActionPerformed
        // TODO add your handling code here:
        AgregarDetalleFactura();
    }//GEN-LAST:event_butt_agregarDetalleActionPerformed

    private void butt_crearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_crearFacturaActionPerformed
        // TODO add your handling code here:
        RegistrarFactura();
    }//GEN-LAST:event_butt_crearFacturaActionPerformed

    private void butt_eliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_eliminarPersonaActionPerformed
        // TODO add your handling code here:
        EliminarPersona();
    }//GEN-LAST:event_butt_eliminarPersonaActionPerformed

    private void butt_eliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_eliminarProdActionPerformed
        // TODO add your handling code here:
        EliminarDetalleFactura();
    }//GEN-LAST:event_butt_eliminarProdActionPerformed

    private void EliminarDetalleFactura() {
        int filaSeleccionada = tbl_detalle.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Eliminar de la lista
            detallesFactura.remove(filaSeleccionada);

            // Eliminar de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tbl_detalle.getModel();
            modelo.removeRow(filaSeleccionada);

            // Desactivar botón si ya no hay productos
            if (detallesFactura.isEmpty()) {
                butt_eliminarProd.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
        }
    }

    private void EliminarPersona() {
        int filaSeleccionada = tbl_persona.getSelectedRow();
        if (filaSeleccionada != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tbl_persona.getModel();
            modelo.removeRow(filaSeleccionada);
            butt_eliminarPersona.setEnabled(false);
            butt_buscarCedula.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
        }
    }

    private void BuscarPersona() {
        String cedula = this.txt_cedula.getText();
        this.personaEncontrada = this.servicio.BuscarPersonaPorCedula(cedula);
        if (this.personaEncontrada != null) {
            System.out.println("lA persona que se ancla la factura es: " + this.personaEncontrada.getNombre());
            // Crear un nuevo modelo de tabla
            modelo = new DefaultTableModel();
            modelo.addColumn("Cédula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Edad");

            Object[] fila = {
                personaEncontrada.getCedula(),
                personaEncontrada.getNombre(),
                personaEncontrada.getApellido(),
                personaEncontrada.getEdad()
            };

            modelo.addRow(fila);

            // Asignar el modelo a la tabla
            tbl_persona.setModel(modelo);
            txt_cedula.setText("");
            butt_buscarCedula.setEnabled(false);
            butt_eliminarPersona.setEnabled(true);
            butt_buscarCodigo.setEnabled(true);

        }
    }

    private void AgregarProductoTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");

        for (DetalleFactura detalle : detallesFactura) {
            Object[] fila = {
                detalle.getProducto().getCodigo(),
                detalle.getProducto().getNombre(),
                detalle.getProducto().getPrecio(),
                detalle.getCantidad()
            };
            modelo.addRow(fila);
        }

        tbl_detalle.setModel(modelo);
        txt_codigo.setText("");
        butt_agregarDetalle.setEnabled(false);
        butt_crearFactura.setEnabled(true);
    }

    private void BuscarProducto() {
        String codigo = this.txt_codigo.getText();
        this.productoEncontrado = this.servicio.BuscarProductoPorCodigo(codigo);

        if (this.productoEncontrado != null) {
            System.out.println("El producto encontrado es: " + productoEncontrado.getNombre());
            this.txt_precio.setText(String.valueOf(this.productoEncontrado.getPrecio()));
            lb_infProducto.setText("Producto Encontrado");
            butt_agregarDetalle.setEnabled(true);
        } else {
            lb_infProducto.setText("Producto NO Encontrado");
            butt_agregarDetalle.setEnabled(false);
        }

        // Temporizador con expresión lambda
        new Timer(3000, e -> lb_infProducto.setText("")).start();
    }

    private void AgregarDetalleFactura() {
        int cantidad = Integer.parseInt(this.txt_cantidad.getText());
        if (this.productoEncontrado != null) {
            // int cantidad, float precioUnitario, Producto producto
            DetalleFactura nuevoDetalle = new DetalleFactura(cantidad,
                    this.productoEncontrado.getPrecio(), this.productoEncontrado);
            this.detallesFactura.add(nuevoDetalle);

            for (DetalleFactura actualDetalle : this.detallesFactura) {
                System.out.println("Detalle: " + actualDetalle.getProducto().getNombre()
                        + ", " + actualDetalle.getProducto().getPrecio());
            }

            AgregarProductoTabla();
            txt_cantidad.setText("");
            txt_precio.setText("");
            butt_eliminarProd.setEnabled(true);
        }
    }

    private void LimpiarTablas() {
        // Limpiar tabla de persona
        DefaultTableModel modeloPersona = (DefaultTableModel) tbl_persona.getModel();
        modeloPersona.setRowCount(0);

        // Limpiar tabla de detalles
        DefaultTableModel modeloDetalle = (DefaultTableModel) tbl_detalle.getModel();
        modeloDetalle.setRowCount(0);

        // Limpiar la lista de detalles
        detallesFactura.clear();
    }

    private void RegistrarFactura() {
        if (this.personaEncontrada != null && this.detallesFactura.size() > 0) {
            // Persona persona, List<DetalleFactura> detalles
            Factura nuevaFactura = new Factura(this.personaEncontrada, this.detallesFactura);
            this.servicio.RegistrarNuevaFactura(nuevaFactura);
            LimpiarTablas();
            DeshabilitarBotones();
            JOptionPane.showMessageDialog(null, "Factura registrada con exito");
        } else {
            JOptionPane.showMessageDialog(null, "Error interno");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_agregarDetalle;
    private javax.swing.JButton butt_buscarCedula;
    private javax.swing.JButton butt_buscarCodigo;
    private javax.swing.JButton butt_crearFactura;
    private javax.swing.JButton butt_eliminarPersona;
    private javax.swing.JButton butt_eliminarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_infProducto;
    private javax.swing.JTable tbl_detalle;
    private javax.swing.JTable tbl_persona;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
